CREATE TABLE LEVELTICKET (
  LEVELTICKET_ID INTEGER auto_increment,
  LEVEL          VARCHAR(20),
  PRIMARY KEY (LEVELTICKET_ID)
);

CREATE TABLE SIT (
  SIT_ID         INTEGER auto_increment,
  FOREIGN KEY (PLANE_ID)REFERENCES PLANE (PLANE_ID),
  FOREIGN KEY (LEVELTICKET_ID)REFERENCES LEVELTICKET (LEVELTICKET_ID),
  PLACE          VARCHAR(10),
  PRIMARY KEY (SIT_ID)
);

DELETE FROM TICKET;
DELETE FROM FLIGHTPRICE;

ALTER TABLE flightprice ALTER COLUMN flightprice_id RESTART WITH 1;
ALTER TABLE ticket ALTER COLUMN number RESTART WITH 1;

ALTER TABLE TICKET
  DROP COLUMN PLACE;
ALTER TABLE TICKET
  DROP COLUMN flightprice_id;
ALTER TABLE TICKET
  ADD FOREIGN KEY (SIT_ID ) REFERENCES SIT (SIT_ID);
ALTER TABLE FLIGHTPRICE
  DROP COLUMN LEVEL;
ALTER TABLE FLIGHTPRICE
  ADD FOREIGN KEY (LEVELTICKET_ID)  REFERENCES LEVELTICKET (LEVELTICKET_ID);


ALTER TABLE USERAIRLINE
    ADD COLUMN ENABLED BOOLEAN DEFAULT TRUE;