CREATE USER EvgenyK WITH
  PASSWORD '123456';
GRANT ALL ON ALL TABLES IN SCHEMA public TO evgenyk;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO evgenyk;

CREATE DATABASE AIRPORT WITH
  OWNER = evgenyk;