CREATE USER EvgenyK WITH
  PASSWORD '123456';

CREATE DATABASE AIRLINE WITH
  OWNER = evgenyk;
CREATE SEQUENCE hibernate_sequence START 1;
GRANT ALL ON ALL TABLES IN SCHEMA public TO evgenyk;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO evgenyk;