INSERT INTO AIRLINE (NAME) VALUES ('Qatar Airways');

INSERT INTO PLANE (NAME, CAPACITY) VALUES ('Boeing 747', 500);
INSERT INTO PLANE (NAME, CAPACITY) VALUES ('Airbus A320', 700);

INSERT INTO PASSENGER (LASTNAME, FIRSTNAME, PATRONYM, PASSPORTNUMBER)
VALUES ('Chirkin', 'Alexander', 'Ivanovich', '48524788932');
INSERT INTO PASSENGER (LASTNAME, FIRSTNAME, PATRONYM, PASSPORTNUMBER)
VALUES ('Kirillova', 'Svetlana', 'Igorevna', '42314568213');
INSERT INTO PASSENGER (LASTNAME, FIRSTNAME, PATRONYM, PASSPORTNUMBER)
VALUES ('Kozlov', 'Sergey', 'Nikolaevich', '41237856321');

INSERT INTO AIRPORT (NAME) VALUES ('London, airport Heathrow');
INSERT INTO AIRPORT (NAME) VALUES ('Berlin, airport Tegel');
INSERT INTO AIRPORT (NAME) VALUES ('Stockholm, airport Arlanda');
INSERT INTO AIRPORT (NAME) VALUES ('Barcelona, airport El Prat');

INSERT INTO FLIGHT (NUMBER, PLANE_ID, DEPARTURE_AIRPORT_ID, ARRIVAL_AIRPORT_ID, AIRLINE_ID, DATE, TIME)
VALUES ('1574', 1, 1, 3, 1, '2018-10-01', '8:05');
INSERT INTO FLIGHT (NUMBER, PLANE_ID, DEPARTURE_AIRPORT_ID, ARRIVAL_AIRPORT_ID, AIRLINE_ID, DATE, TIME)
VALUES ('2587', 2, 2, 4, 1, '2018-10-02', '16:40');

INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVEL, PRICE) VALUES (1, 'Econom', 10000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVEL, PRICE) VALUES (2, 'Econom', 10000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVEL, PRICE) VALUES (1, 'Business', 30000);

INSERT INTO TICKET (FLIGHT_ID, FLIGHTPRICE_ID, PLACE, PASSENGER_ID) VALUES (1, 1, '35H', 1);
INSERT INTO TICKET (FLIGHT_ID, FLIGHTPRICE_ID, PLACE, PASSENGER_ID) VALUES (1, 2, '42B', 2);
INSERT INTO TICKET (FLIGHT_ID, FLIGHTPRICE_ID, PLACE, PASSENGER_ID) VALUES (2, 3, '2A', 3);