INSERT INTO ROLE (NAME) VALUES ('user');
INSERT INTO ROLE (NAME) VALUES ('admin');
INSERT INTO ROLE (NAME) VALUES ('guest');

INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, PASSENGER_ID, ROLE_ID)
VALUES ('Chir', '457Ch', 'chirkin.a.i@gmail.com', '89154568123', 1, 1);
INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, PASSENGER_ID, ROLE_ID)
VALUES ('KillReal', 'legr56', 'Kirillova.s.i@yandex.ru', '89856931548', 2, 1);
INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, PASSENGER_ID, ROLE_ID)
VALUES ('KozlovSN', 'spiderman15', 'kozlovSN@gmaol.com', '89004567893', 3, 1);