CREATE USER EvgenyK WITH
  PASSWORD '123456';

CREATE DATABASE AIRLINE WITH
OWNER = evgenyk;

GRANT ALL ON ALL TABLES IN SCHEMA public TO evgenyk;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO evgenyk;