INSERT INTO AIRLINE (NAME) VALUES ('Qatar Airways');

INSERT INTO PLANE (NAME, CAPACITY) VALUES ('Boeing 747', 500);
INSERT INTO PLANE (NAME, CAPACITY) VALUES ('Airbus A320', 700);

INSERT INTO AIRPORT (NAME) VALUES ('London, airport Heathrow');
INSERT INTO AIRPORT (NAME) VALUES ('Berlin, airport Tegel');
INSERT INTO AIRPORT (NAME) VALUES ('Stockholm, airport Arlanda');
INSERT INTO AIRPORT (NAME) VALUES ('Barcelona, airport El Prat');

INSERT INTO FLIGHT (NUMBER, PLANE_ID, DEPARTURE_AIRPORT_ID, ARRIVAL_AIRPORT_ID, AIRLINE_ID, DATE, TIME)
VALUES ('1574', 1, 1, 3, 1, '2018-10-01', '8:05');
INSERT INTO FLIGHT (NUMBER, PLANE_ID, DEPARTURE_AIRPORT_ID, ARRIVAL_AIRPORT_ID, AIRLINE_ID, DATE, TIME)
VALUES ('2587', 2, 2, 4, 1, '2018-10-02', '16:40');
INSERT INTO FLIGHT (NUMBER, PLANE_ID, DEPARTURE_AIRPORT_ID, ARRIVAL_AIRPORT_ID, DATE, TIME)
VALUES ('1574', 1, 1, 3, '2018-11-05', '8:05');

INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVEL, PRICE) VALUES (1, 'Econom', 10000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVEL, PRICE) VALUES (2, 'Econom', 10000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVEL, PRICE) VALUES (1, 'Business', 30000);

INSERT INTO ROLE (NAME) VALUES ('user');
INSERT INTO ROLE (NAME) VALUES ('admin');
INSERT INTO ROLE (NAME) VALUES ('guest');

INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, ROLE_ID,LASTNAME, FIRSTNAME, PATRONYM, PASSPORTNUMBER)
VALUES ('Chir', '$2a$10$CXmiUd9X5XkdYmJ1MXyGIO.80IU5msW/4ZARN8Vwe3yHTWGpB8lXC', 'chirkin.a.i@gmail.com', '89154568123', 1,'Chirkin', 'Alexander', 'Ivanovich', '48524788932');
INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, ROLE_ID,LASTNAME, FIRSTNAME, PATRONYM, PASSPORTNUMBER)
VALUES ('KillReal', '$2a$10$qB05ctQ7fWGJHcsdXHScH.LnNEnDAOvXfm/Y1qx5J0TFp4.srbo2a', 'Kirillova.s.i@yandex.ru', '89856931548', 1,'Kirillova', 'Svetlana', 'Igorevna', '42314568213');
INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, ROLE_ID,LASTNAME, FIRSTNAME, PATRONYM, PASSPORTNUMBER)
VALUES ('KozlovSN', '$2a$10$VZDiTbeBzVFxOaGWkiPW3.DJcQs5urHsjRxM/dRaLHHKbgzj7.VjW', 'kozlovSN@gmaol.com', '89004567893', 1,'Kozlov', 'Sergey', 'Nikolaevich', '41237856321');

INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, ROLE_ID)
VALUES ('Kabatov', '$2a$10$6kxVX7p8A18EL7G9epY4SuVa3e1.CORlp68Xj/sjkUasp.QJ9j5m6', 'djin94@yandex.ru', '89004564512', 2);

INSERT INTO TICKET (FLIGHT_ID, FLIGHTPRICE_ID, PLACE, USER_ID) VALUES (1, 1, '35H', 1);
INSERT INTO TICKET (FLIGHT_ID, FLIGHTPRICE_ID, PLACE, USER_ID) VALUES (1, 2, '42B', 2);
INSERT INTO TICKET (FLIGHT_ID, FLIGHTPRICE_ID, PLACE, USER_ID) VALUES (2, 3, '2A', 3);