CREATE TABLE ROLE (
  ROLE_ID SERIAL PRIMARY KEY,
  NAME    VARCHAR(50)
);

CREATE TABLE USERAIRLINE (
  USER_ID      SERIAL PRIMARY KEY,
  LOGIN        VARCHAR(50),
  PASSWORD     VARCHAR(100),
  EMAIL        VARCHAR(50),
  PHONE        VARCHAR(30),
  PASSENGER_ID INTEGER REFERENCES PASSENGER (PASSENGER_ID),
  ROLE_ID      INTEGER REFERENCES ROLE (ROLE_ID)
)