INSERT INTO ROLE (NAME) VALUES ('user');
INSERT INTO ROLE (NAME) VALUES ('admin');
INSERT INTO ROLE (NAME) VALUES ('guest');

INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, PASSENGER_ID, ROLE_ID)
VALUES ('Chir', '$2a$10$CXmiUd9X5XkdYmJ1MXyGIO.80IU5msW/4ZARN8Vwe3yHTWGpB8lXC', 'chirkin.a.i@gmail.com', '89154568123', 1, 1);
INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, PASSENGER_ID, ROLE_ID)
VALUES ('KillReal', '$2a$10$qB05ctQ7fWGJHcsdXHScH.LnNEnDAOvXfm/Y1qx5J0TFp4.srbo2a', 'Kirillova.s.i@yandex.ru', '89856931548', 2, 1);
INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, PASSENGER_ID, ROLE_ID)
VALUES ('KozlovSN', '$2a$10$VZDiTbeBzVFxOaGWkiPW3.DJcQs5urHsjRxM/dRaLHHKbgzj7.VjW', 'kozlovSN@gmaol.com', '89004567893', 3, 1);

INSERT INTO USERAIRLINE (LOGIN, PASSWORD, EMAIL, PHONE, ROLE_ID)
VALUES ('Kabatov', '$2a$10$m2uJLciNFr9fMXtWutK5beAw.vkNJjTK7qkfcdxjkv5i3q4Mxy.Ee', 'djin94@yandex.ru', '89004564512', 2);