CREATE TABLE LEVELTICKET (
  LEVELTICKET_ID SERIAL PRIMARY KEY,
  LEVEL          VARCHAR(20)
);

CREATE TABLE SIT (
  SIT_ID         SERIAL PRIMARY KEY,
  PLANE_ID       INTEGER REFERENCES PLANE (PLANE_ID),
  LEVELTICKET_ID INTEGER REFERENCES LEVELTICKET (LEVELTICKET_ID),
  PLACE          VARCHAR(10)
);

DELETE FROM TICKET;
DELETE FROM FLIGHTPRICE;

ALTER SEQUENCE flightprice_flightprice_id_seq RESTART WITH 1;
ALTER SEQUENCE ticket_number_seq RESTART WITH 1;

ALTER TABLE TICKET
  DROP COLUMN PLACE;
ALTER TABLE TICKET
  DROP COLUMN flightprice_id;
ALTER TABLE TICKET
  ADD COLUMN SIT_ID INTEGER REFERENCES SIT (SIT_ID);
ALTER TABLE FLIGHTPRICE
  DROP COLUMN LEVEL;
ALTER TABLE FLIGHTPRICE
  ADD COLUMN LEVELTICKET_ID INTEGER REFERENCES LEVELTICKET (LEVELTICKET_ID);
