INSERT INTO LEVELTICKET (LEVEL) VALUES ('Econom');
INSERT INTO LEVELTICKET (LEVEL) VALUES ('Business');

INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (1, 1, '12A');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (1, 1, '12C');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (1, 1, '15E');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (1, 1, '16B');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (1, 2, '2A');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (1, 2, '4B');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (1, 2, '4D');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (2, 1, '14A');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (2, 1, '16D');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (2, 1, '18G');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (2, 1, '25A');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (2, 2, '2A');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (2, 2, '2C');
INSERT INTO SIT (PLANE_ID, LEVELTICKET_ID, PLACE) VALUES (2, 2, '4A');

INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVELTICKET_ID, PRICE) VALUES (1, 1, 10000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVELTICKET_ID, PRICE) VALUES (1, 2, 30000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVELTICKET_ID, PRICE) VALUES (2, 1, 10000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVELTICKET_ID, PRICE) VALUES (2, 2, 30000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVELTICKET_ID, PRICE) VALUES (3, 1, 10000);
INSERT INTO FLIGHTPRICE (FLIGHT_ID, LEVELTICKET_ID, PRICE) VALUES (3, 2, 30000);


INSERT INTO TICKET (FLIGHT_ID, SIT_ID, USER_ID) VALUES (1, 1, 1);
INSERT INTO TICKET (FLIGHT_ID, SIT_ID, USER_ID) VALUES (1, 5, 2);
INSERT INTO TICKET (FLIGHT_ID, SIT_ID, USER_ID) VALUES (2, 9, 3);